# -*- coding: utf-8 -*-
"""prak3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HMnz_cKwZeJydMFWDwmpBkGLvv5tW22b
"""

import numpy as np
from scipy.stats import multinomial

n_trials_nama = 10
probabilitas_nama = [0.2, 0.3, 0.5]

multinom_dist = multinomial(n_trials_nama, probabilitas_nama)

sampel = multinom_dist.rvs()

print("sampel hasil percobaan: ")
print(sampel)

pmf_sampel = multinom_dist.pmf(sampel)
print("probabilitas massa dari sampel yang dihasilkan: ", pmf_sampel)

from scipy.stats import multinomial

n_trials = 20
probabilities = [8/20, 6/20, 6/20]

multinom_dist = multinomial(n_trials, probabilities)

outcome = [8, 6, 6]
pmf_outcome = multinom_dist.pmf(outcome)

print("probabilitas massa: ", pmf_outcome)

import numpy as np
from scipy.stats import hypergeom

N = 50
K = 20
n = 10
k = 5

hypergeom_dist = hypergeom(N, K, n)

pmf_value = hypergeom_dist.pmf(k)
print("probabilitas massa: ", pmf_value)

from scipy.stats import hypergeom

N = 30
K = 10
n = 8
k1 = 3
k2 = 2
k3 = 3

hypergeom_dist = hypergeom(N, K, n)

pmf_value = hypergeom_dist.pmf([k1, k2, k3])
print("probabilitas massa: ", pmf_value)

import numpy as np
from scipy.stats import poisson

mu = 2

poisson_dist = poisson (mu)

sampel = poisson_dist.rvs (size=10)
print("sampel hasil distribusi poisson: ")
print(sampel)

pmf_sampel = poisson_dist.pmf(sampel)
print("\nProbabilitas massa dari sampel yg dihasilkan: ", pmf_sampel)

from scipy.stats import poisson

mu = 4

prob_tepat_6 = poisson.pmf(6, mu)
print("peluang bahwa akan tiba tepat 6 paket dalam jam berikutnya: ", prob_tepat_6)